export const EXPENSE_LIST_SELECT = [
  "id",
  "expense_number",
  "title",
  "description",
  "amount",
  "requested_amount",
  "approved_amount",
  "final_amount",
  "currency_code",
  "expense_date",
  "expense_type",
  "status",
  "approval_status",
  "payment_status",
  "request_status",
  "documentation_status",
  "finance_review_status",
  "funding_status",
  "coverage_status",
  "recipient_confirmation_status",
  "company_id",
  "employee_ref_id",
  "expense_made_by_type",
  "responsible_person_name",
  "other_made_by_explanation",
  "expense_source_name",
  "online_platform",
  "online_order_number",
  "online_confirmation_status",
  "verified_for_payment_at",
  "verification_notes",
  "submitter_user_id",
  "created_by",
  "metadata",
  "created_at",
  "updated_at",
].join(", ");

export const EXPENSE_MODULE1_SELECT = [
  "id",
  "expense_number",
  "title",
  "description",
  "amount",
  "currency_code",
  "expense_date",
  "expense_type",
  "status",
  "request_status",
  "documentation_status",
  "finance_review_status",
  "coverage_status",
  "recipient_confirmation_status",
  "company_id",
  "employee_ref_id",
  "expense_made_by_type",
  "responsible_person_name",
  "expense_source_name",
  "online_platform",
  "online_order_number",
  "submitter_user_id",
  "created_by",
  "created_at",
  "updated_at",
].join(", ");

export const FUNDING_BATCH_SELECT =
  "id, batch_number, funding_company_id, funding_bank_account_id, allocation_date, currency_code, allocated_amount, status, documentation_status, notes, created_at, updated_at";

export const PAYMENT_MADE_SELECT = [
  "id",
  "amount",
  "payment_date",
  "payment_method_id",
  "status",
  "reference_number",
  "vendor_id",
  "bill_id",
  "notes",
  "payment_source_type",
  "expense_funding_batch_id",
  "recipient_employee_ref_id",
  "recipient_person_name",
  "recipient_confirmation_status",
  "paid_from_company_id",
  "paid_from_bank_account_id",
  "payment_currency_code",
  "converted_amount",
  "created_at",
  "updated_at",
].join(", ");

export const ALLOCATION_SELECT = [
  "id",
  "payment_made_id",
  "expense_id",
  "funding_batch_id",
  "funding_company_id",
  "paid_from_bank_account_id",
  "recipient_employee_ref_id",
  "recipient_person_name",
  "allocated_amount",
  "currency_code",
  "payment_currency_code",
  "converted_amount",
  "recipient_confirmation_status",
  "lifecycle_status",
  "metadata",
  "created_at",
  "updated_at",
].join(", ");
