import type { FinanceReportDefinition } from "./types";

export const FINANCE_REPORT_CATALOG: FinanceReportDefinition[] = [
  {
    key: "trial-balance",
    title: "Trial Balance",
    description:
      "Read-only balance view by account across your accounting structure.",
    route: "/finance/reports/trial-balance",
    rpcName: "finance_trial_balance",
    parameters: [],
    columns: [
      { key: "account_code", label: "Code" },
      { key: "account_name", label: "Account" },
      { key: "account_type", label: "Type" },
      { key: "total_debit", label: "Debit", align: "right", format: "money" },
      { key: "total_credit", label: "Credit", align: "right", format: "money" },
      { key: "balance", label: "Balance", align: "right", format: "money" },
    ],
    readOnly: true,
    statusLabel: "Live",
  },
  {
    key: "ar-aging",
    title: "AR Aging",
    description:
      "Receivables aging buckets for collections and overdue tracking.",
    route: "/finance/reports/ar-aging",
    rpcName: "finance_ar_aging",
    parameters: [],
    columns: [
      { key: "invoice_number", label: "Invoice" },
      { key: "aging_bucket", label: "Bucket" },
      { key: "days_overdue", label: "Days Overdue", align: "right", format: "count" },
      { key: "balance_due", label: "Balance", align: "right", format: "money" },
    ],
    readOnly: true,
    statusLabel: "Live",
  },
  {
    key: "ap-aging",
    title: "AP Aging",
    description: "Payables aging buckets for outgoing payment planning.",
    route: "/finance/reports/ap-aging",
    rpcName: "finance_ap_aging",
    parameters: [],
    columns: [
      { key: "bill_number", label: "Bill" },
      { key: "aging_bucket", label: "Bucket" },
      { key: "days_overdue", label: "Days Overdue", align: "right", format: "count" },
      { key: "balance_due", label: "Balance", align: "right", format: "money" },
    ],
    readOnly: true,
    statusLabel: "Live",
  },
  {
    key: "ledger",
    title: "Ledger Views",
    description: "Journal entry and line-level ledger analysis.",
    route: "/finance/reports/ledger",
    parameters: [
      { key: "date_from", label: "From", type: "date" },
      { key: "date_to", label: "To", type: "date" },
    ],
    columns: [
      { key: "entry_date", label: "Date", format: "date" },
      { key: "entry_number", label: "Entry" },
      { key: "account_code", label: "Account" },
      { key: "description", label: "Description" },
      { key: "debit", label: "Debit", align: "right", format: "money" },
      { key: "credit", label: "Credit", align: "right", format: "money" },
    ],
    readOnly: true,
    statusLabel: "Live",
  },
  {
    key: "categories",
    title: "Categories",
    description: "Revenue and expense category analytics.",
    route: "/finance/reports/categories",
    rpcNames: ["finance_revenue_by_category", "finance_expense_by_category"],
    parameters: [],
    columns: [
      { key: "category_name", label: "Category" },
      { key: "category_code", label: "Code" },
      { key: "source_type", label: "Source" },
      { key: "total_amount", label: "Total", align: "right", format: "money" },
    ],
    readOnly: true,
    statusLabel: "Live",
  },
  {
    key: "payroll",
    title: "Payroll Summary",
    description: "Payroll run analytics, payment status, and totals.",
    route: "/finance/reports/payroll",
    rpcName: "finance_payroll_summary",
    parameters: [],
    columns: [
      { key: "run_number", label: "Run" },
      { key: "status", label: "Status" },
      {
        key: "payroll_payment_count",
        label: "Payments",
        align: "right",
        format: "count",
      },
      { key: "total_net", label: "Net Total", align: "right", format: "money" },
    ],
    readOnly: true,
    statusLabel: "Live",
  },
  {
    key: "project",
    title: "Project Financial View",
    description:
      "Project-linked revenue, expenses, payroll, and net operating position.",
    route: "/finance/reports/project",
    rpcName: "finance_project_financial_view",
    parameters: [],
    columns: [
      { key: "project_name", label: "Project" },
      { key: "invoice_revenue", label: "Revenue", align: "right", format: "money" },
      { key: "expenses_total", label: "Expenses", align: "right", format: "money" },
      { key: "payroll_total", label: "Payroll", align: "right", format: "money" },
      {
        key: "net_operating_position",
        label: "Net",
        align: "right",
        format: "money",
      },
    ],
    readOnly: true,
    statusLabel: "Live",
  },
  {
    key: "incoming-money",
    title: "Incoming Money Flow",
    description:
      "Customer receivables flow from quotation and commitment through invoice and payment collection.",
    route: "/finance/reports/incoming-money",
    rpcName: "finance_ar_aging",
    parameters: [],
    columns: [
      { key: "invoice_number", label: "Invoice" },
      { key: "aging_bucket", label: "Bucket" },
      { key: "days_overdue", label: "Days Overdue", align: "right", format: "count" },
      { key: "balance_due", label: "Balance", align: "right", format: "money" },
    ],
    readOnly: true,
    statusLabel: "Live",
  },
  {
    key: "supplier-procurement",
    title: "Supplier Procurement Flow",
    description:
      "Supplier payable flow from vendor quotation through purchase order, vendor PI / invoice, and payment.",
    route: "/finance/reports/supplier-procurement",
    rpcName: "finance_ap_aging",
    parameters: [],
    columns: [
      { key: "bill_number", label: "Bill" },
      { key: "aging_bucket", label: "Bucket" },
      { key: "days_overdue", label: "Days Overdue", align: "right", format: "count" },
      { key: "balance_due", label: "Balance", align: "right", format: "money" },
    ],
    readOnly: true,
    statusLabel: "Live",
  },
  {
    key: "expenses",
    title: "Expenses Flow",
    description: "Operating expense and reimbursement activity by category and source.",
    route: "/finance/reports/expenses",
    rpcName: "finance_expense_by_category",
    parameters: [],
    columns: [
      { key: "category_name", label: "Category" },
      { key: "category_code", label: "Code" },
      { key: "source_type", label: "Source" },
      { key: "total_amount", label: "Total", align: "right", format: "money" },
    ],
    readOnly: true,
    statusLabel: "Live",
  },
  {
    key: "cash-movement",
    title: "Cash Movement",
    description: "Payments in, payments out, and net cash movement for the current reporting period.",
    route: "/finance/reports/cash-movement",
    rpcName: "finance_reports_overview",
    parameters: [],
    columns: [
      { key: "metric", label: "Metric" },
      { key: "amount", label: "Amount", align: "right", format: "money" },
    ],
    readOnly: true,
    statusLabel: "Live",
  },
  {
    key: "export",
    title: "Financial Reports Export",
    description:
      "Generate and download full financial reports across dates, projects, and accounting structures.",
    route: "/finance/reports/export",
    parameters: [
      { key: "date_from", label: "From", type: "date" },
      { key: "date_to", label: "To", type: "date" },
    ],
    columns: [
      { key: "report_name", label: "Report" },
      { key: "status", label: "Status" },
      { key: "generated_at", label: "Generated", format: "date" },
    ],
    readOnly: true,
    statusLabel: "Live",
  },
];

export function getFinanceReportDefinition(reportKey: string) {
  return FINANCE_REPORT_CATALOG.find((report) => report.key === reportKey) ?? null;
}
