/**
 * AgentOps Tools Hub registry — single source of truth for hub cards and navigation.
 * Add/remove tools here. Do not hardcode Tools Hub cards inside page JSX.
 */

export type ToolRegistryLevel = 1 | 2 | 3;

export type ToolRegistryNodeType =
  | "category"
  | "group"
  | "tool"
  | "memory-area"
  | "runtime-service"
  | "reference";

export type ToolRegistryStatus =
  | "existing"
  | "partial"
  | "placeholder"
  | "cloned-only"
  | "needs-setup"
  | "planned"
  | "target-only"
  | "not-installed";

export type ToolRegistryEntry = {
  id: string;
  title: string;
  description: string;
  level: ToolRegistryLevel;
  parentId: string | null;
  categoryId: string | null;
  childrenIds: string[];
  type: ToolRegistryNodeType;
  currentRuntime: string;
  targetRuntime: string;
  sourceType: string;
  sourcePath?: string;
  sourceUrl?: string;
  status: ToolRegistryStatus;
  installedStatus: string;
  configuredStatus: string;
  usedBy: string[];
  dataLocation: string;
  relatedToolIds: string[];
  route?: string;
  notes?: string;
};

export const TOOLS_HUB_BASE_PATH = "/system/agent-ops/tools";

/** Flat registry keyed by id. */
const TOOL_REGISTRY_ENTRIES: Record<string, ToolRegistryEntry> = {
  // ─── Level 1: main categories ─────────────────────────────────────────────
  "agent-brain-memory": {
    id: "agent-brain-memory",
    title: "Agent Brain & Memory",
    description:
      "Global rules, per-agent memory, coordination tools, context understanding, evidence, and reasoning layers.",
    level: 1,
    parentId: null,
    categoryId: "agent-brain-memory",
    childrenIds: [
      "global-memory",
      "per-agent-memory",
      "memory-coordination-tools",
      "code-context-understanding",
      "evidence-tools",
      "reasoning-layer",
    ],
    type: "category",
    currentRuntime: "Hybrid — Supabase + repo files + planned Hermes",
    targetRuntime: "Owner-gated advisory memory with Hermes and AgentMemory",
    sourceType: "internal-app",
    status: "partial",
    installedStatus: "AgentOps memory tables and UI exist; live sync off",
    configuredStatus: "Database-only MVP; Hermes/AgentMemory not connected",
    usedBy: ["AgentOps", "Cursor agents", "QA agents"],
    dataLocation: "Supabase agentops_agent_memory + qa-agent/agent-memory/",
    relatedToolIds: ["hermes", "agentmemory", "codegraph"],
    route: `${TOOLS_HUB_BASE_PATH}/agent-brain-memory`,
    notes: "Only category with Level 3 nested groups in Phase 1.",
  },
  "chat-voice": {
    id: "chat-voice",
    title: "Chat & Voice Tools",
    description: "Local LLM chat, speech input/output, and future avatar/voice surfaces.",
    level: 1,
    parentId: null,
    categoryId: "chat-voice",
    childrenIds: ["chat-local-llm", "chat-stt", "chat-tts", "chat-supertonic", "chat-avatar-later"],
    type: "category",
    currentRuntime: "Hybrid — Ollama proxy staging; voice inactive",
    targetRuntime: "Local LLM + on-device TTS/STT when approved",
    sourceType: "internal-app",
    status: "partial",
    installedStatus: "Local LLM adapter exists; Supertonic not cloned",
    configuredStatus: "Env-gated; Council shows voice as future/inactive",
    usedBy: ["AgentOps Council", "Issue Workspace", "AI Management"],
    dataLocation: "Supabase owner feedback metadata + local Ollama",
    relatedToolIds: ["local-llm", "supertonic"],
    route: `${TOOLS_HUB_BASE_PATH}/chat-voice`,
  },
  "website-qa-evidence": {
    id: "website-qa-evidence",
    title: "Website QA & Evidence Runtime",
    description: "Browser QA, Playwright, reports, verification runners, and evidence capture.",
    level: 1,
    parentId: null,
    categoryId: "website-qa-evidence",
    childrenIds: [
      "qa-browser-runner",
      "qa-playwright-runner",
      "qa-crawler",
      "qa-visual-qa",
      "qa-reports-storage",
      "qa-verification-runner",
    ],
    type: "category",
    currentRuntime: "Local Computer — manual npm scripts",
    targetRuntime: "Staging browser QA with owner-approved imports",
    sourceType: "internal-app",
    status: "partial",
    installedStatus: "qa-agent scripts and Playwright dep in package.json",
    configuredStatus: "No automated scheduler; reports path often empty until runs",
    usedBy: ["AgentOps automation", "QA orchestrator", "Piter"],
    dataLocation: "qa-agent/reports/ (gitignored when generated)",
    relatedToolIds: ["browser-qa", "playwright"],
    route: `${TOOLS_HUB_BASE_PATH}/website-qa-evidence`,
  },
  "build-development": {
    id: "build-development",
    title: "Build & Development Tools",
    description: "Cursor, MCP servers, guardrails, and local build/QA scripts for AiXia development.",
    level: 1,
    parentId: null,
    categoryId: "build-development",
    childrenIds: [
      "build-cursor",
      "build-github-tools",
      "build-supabase-mcp",
      "build-vercel-mcp",
      "build-codegraph-mcp",
      "build-local-scripts",
    ],
    type: "category",
    currentRuntime: "Local Computer + Cursor MCP",
    targetRuntime: "Registry-driven builder toolchain with honest status gates",
    sourceType: "hybrid",
    status: "partial",
    installedStatus: "CodeGraph MCP configured; GitHub Actions not in repo",
    configuredStatus: "Build guardrails run on npm run build",
    usedBy: ["Cursor agents", "Piter", "CI (planned)"],
    dataLocation: "Repo files + .codegraph/ + registry/",
    relatedToolIds: ["codegraph-mcp", "aixia-guardrails"],
    route: `${TOOLS_HUB_BASE_PATH}/build-development`,
  },
  "design-crew-references": {
    id: "design-crew-references",
    title: "Design Crew & References",
    description: "Design reference repos, aixia-global law, and visual QA guardrail mirrors.",
    level: 1,
    parentId: null,
    categoryId: "design-crew-references",
    childrenIds: [
      "design-shadcn-admin",
      "design-tailadmin-react",
      "design-tailadmin-multi",
      "design-aixia-global-sot",
      "design-visual-qa-rules",
    ],
    type: "category",
    currentRuntime: "Local Computer — sibling reference clones",
    targetRuntime: "Read-only reference + aixia-global as implementation law",
    sourceType: "hybrid",
    status: "existing",
    installedStatus: "reference/ clones present; node_modules not installed",
    configuredStatus: "aixia-global is active law inside AiXia-github",
    usedBy: ["Cursor agents", "Design migration", "Guardrails"],
    dataLocation: "src/design-system/aixia-global/ + ../reference/",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/design-crew-references`,
  },
  "automation-integrations": {
    id: "automation-integrations",
    title: "Automation & Integrations",
    description: "Future external actions, webhooks, notifications, and workflow bridges.",
    level: 1,
    parentId: null,
    categoryId: "automation-integrations",
    childrenIds: [
      "auto-zapier",
      "auto-webhooks",
      "auto-api-connectors",
      "auto-notifications",
      "auto-github-actions-later",
    ],
    type: "category",
    currentRuntime: "Placeholder — manual AgentOps automation requests only",
    targetRuntime: "Owner-approved integrations with security review",
    sourceType: "planned",
    status: "planned",
    installedStatus: "AgentOps automation control requests in UI only",
    configuredStatus: "Scheduler preparation-only; Zapier blocked in registry",
    usedBy: ["AgentOps automation page"],
    dataLocation: "Supabase owner feedback metadata",
    relatedToolIds: ["zapier-mcp"],
    route: `${TOOLS_HUB_BASE_PATH}/automation-integrations`,
  },
  "runtime-platform": {
    id: "runtime-platform",
    title: "Runtime & Platform Tools",
    description: "Supabase, Vercel, auth, database, storage, realtime, and edge/worker surfaces.",
    level: 1,
    parentId: null,
    categoryId: "runtime-platform",
    childrenIds: [
      "runtime-supabase",
      "runtime-vercel",
      "runtime-auth",
      "runtime-database",
      "runtime-storage",
      "runtime-realtime",
      "runtime-edge-functions",
      "runtime-background-workers",
    ],
    type: "category",
    currentRuntime: "Cloud + Supabase data layer",
    targetRuntime: "Stable staging/production platform for AiXia app",
    sourceType: "internal-app",
    status: "existing",
    installedStatus: "Supabase client and migrations in AiXia-github",
    configuredStatus: "MCP advisory only; no auto-migrations from agents",
    usedBy: ["AiXia app", "AgentOps", "Cursor Supabase MCP"],
    dataLocation: "Supabase",
    relatedToolIds: ["supabase-mcp", "vercel-mcp"],
    route: `${TOOLS_HUB_BASE_PATH}/runtime-platform`,
  },

  // ─── Level 2: Agent Brain & Memory groups ─────────────────────────────────
  "global-memory": {
    id: "global-memory",
    title: "Global Memory",
    description: "Shared rules, design law, workflows, and owner instructions for all agents.",
    level: 2,
    parentId: "agent-brain-memory",
    categoryId: "agent-brain-memory",
    childrenIds: [
      "gm-website-rules",
      "gm-design-sot",
      "gm-workflow-rules",
      "gm-issue-history",
      "gm-verified-fixes",
      "gm-tool-registry",
      "gm-piter-instructions",
    ],
    type: "group",
    currentRuntime: "Repo files + Supabase findings",
    targetRuntime: "Hermes-assisted recall with aixia-global authority",
    sourceType: "internal-app",
    status: "partial",
    installedStatus: "Docs and AgentOps findings exist",
    configuredStatus: "Not live-synced to Hermes",
    usedBy: ["All agents"],
    dataLocation: "Repo files + Supabase",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/agent-brain-memory/global-memory`,
    notes:
      "Registry taxonomy only — hidden from Agent Brain & Memory hub grid. Global Website Memory layer is owned by Hermes.",
  },
  "per-agent-memory": {
    id: "per-agent-memory",
    title: "Per-Agent Memory",
    description: "Role, permissions, focus, and history scoped to each synthetic agent.",
    level: 2,
    parentId: "agent-brain-memory",
    categoryId: "agent-brain-memory",
    childrenIds: [
      "pam-agent-role",
      "pam-permissions",
      "pam-allowed-tools",
      "pam-module-responsibility",
      "pam-findings-history",
      "pam-current-focus",
      "pam-learned-lessons",
    ],
    type: "group",
    currentRuntime: "Supabase agentops_agent_memory",
    targetRuntime: "Per-agent files + optional AgentMemory recall",
    sourceType: "internal-app",
    status: "partial",
    installedStatus: "AgentOps agents UI and memory export scripts",
    configuredStatus: "Read-only hub v1; export dry-run only; live sync off; AgentMemory not connected",
    usedBy: ["AgentOps agents workspace"],
    dataLocation: "Supabase + qa-agent/agent-memory/",
    relatedToolIds: ["agentmemory"],
    route: `${TOOLS_HUB_BASE_PATH}/agent-brain-memory/per-agent-memory`,
    notes:
      "Registry taxonomy only — hidden from Agent Brain & Memory hub grid. Per-Agent Memory Support layer is owned by Hermes.",
  },
  "memory-coordination-tools": {
    id: "memory-coordination-tools",
    title: "Memory & Coordination Tools",
    description: "Hermes and AgentMemory coordination for advisory context (not law).",
    level: 2,
    parentId: "agent-brain-memory",
    categoryId: "agent-brain-memory",
    childrenIds: ["mct-hermes", "mct-agentmemory"],
    type: "group",
    currentRuntime: "Mock fallback / not connected",
    targetRuntime: "Staging Hermes advisory + AgentMemory recall",
    sourceType: "hybrid",
    status: "needs-setup",
    installedStatus: "Hermes adapter contracts exist; AgentMemory not cloned in tools/",
    configuredStatus: "HERMES_RUNTIME_ACTIVE not evidenced as on",
    usedBy: ["Issue Workspace", "Council"],
    dataLocation: "qa-agent/hermes/ + planned ../tools/agentmemory/",
    relatedToolIds: ["hermes", "agentmemory"],
    route: `${TOOLS_HUB_BASE_PATH}/agent-brain-memory/memory-coordination-tools`,
  },
  "code-context-understanding": {
    id: "code-context-understanding",
    title: "Code / Context Understanding Tools",
    description: "Structural and semantic code intelligence for agents and owners.",
    level: 2,
    parentId: "agent-brain-memory",
    categoryId: "agent-brain-memory",
    childrenIds: ["ccu-codegraph", "ccu-understand-anything", "ccu-claude-context"],
    type: "group",
    currentRuntime: "CodeGraph MCP local; UA/cc cloned only",
    targetRuntime: "CodeGraph read-only staging + optional UA/cc advisory",
    sourceType: "hybrid",
    status: "partial",
    installedStatus: "CodeGraph index files present; UA/cc in ../tools/ cloned only",
    configuredStatus: "App CodeGraph runtime hardcoded off",
    usedBy: ["Cursor", "Issue Workspace discovery panel"],
    dataLocation: ".codegraph/ + ../tools/",
    relatedToolIds: ["codegraph", "understand-anything", "claude-context"],
    route: `${TOOLS_HUB_BASE_PATH}/agent-brain-memory/code-context-understanding`,
  },
  "evidence-tools": {
    id: "evidence-tools",
    title: "Evidence Tools",
    description: "Browser QA artifacts, guardrails, reports, and verification outcomes.",
    level: 2,
    parentId: "agent-brain-memory",
    categoryId: "agent-brain-memory",
    childrenIds: [
      "et-browser-qa",
      "et-playwright",
      "et-reports",
      "et-guardrails",
      "et-verification-results",
    ],
    type: "group",
    currentRuntime: "Local scripts + repo reports path",
    targetRuntime: "Structured evidence linked to AgentOps findings",
    sourceType: "internal-app",
    status: "partial",
    installedStatus: "Scripts exist; report artifacts not in checkout",
    configuredStatus: "Manual import and verification only",
    usedBy: ["AgentOps", "QA orchestrator"],
    dataLocation: "qa-agent/reports/ + Supabase evidence_files",
    relatedToolIds: ["browser-qa", "aixia-guardrails"],
    route: `${TOOLS_HUB_BASE_PATH}/agent-brain-memory/evidence-tools`,
  },
  "reasoning-layer": {
    id: "reasoning-layer",
    title: "Reasoning Layer",
    description: "Human and model reasoning surfaces used to plan, fix, and verify AiXia work.",
    level: 2,
    parentId: "agent-brain-memory",
    categoryId: "agent-brain-memory",
    childrenIds: [
      "rl-cursor",
      "rl-smart-cloud-llm",
      "rl-strong-local-llm-later",
      "rl-task-specific-model",
    ],
    type: "group",
    currentRuntime: "Cursor + mock/optional Ollama",
    targetRuntime: "Layered reasoning with owner approval gates",
    sourceType: "hybrid",
    status: "partial",
    installedStatus: "Cursor workspace active; cloud LLM via product routers elsewhere",
    configuredStatus: "No auto-Cursor from AgentOps",
    usedBy: ["Piter", "Cursor agents", "AgentOps chat adapters"],
    dataLocation: "None in registry — session-based",
    relatedToolIds: ["local-llm", "hermes"],
    route: `${TOOLS_HUB_BASE_PATH}/agent-brain-memory/reasoning-layer`,
  },

  // ─── Level 3: Global Memory ───────────────────────────────────────────────
  "gm-website-rules": {
    id: "gm-website-rules",
    title: "Website rules",
    description: "Module routes, permissions, and website structure memory for agents.",
    level: 3,
    parentId: "global-memory",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "memory-area",
    currentRuntime: "Repo files",
    targetRuntime: "Hermes recall with aixia-global precedence",
    sourceType: "internal-app",
    sourcePath: "qa-agent/design-system/memory/AIXIA_WEBSITE_STRUCTURE_MEMORY.md",
    status: "existing",
    installedStatus: "Memory doc in qa-agent",
    configuredStatus: "Advisory only",
    usedBy: ["QA agents"],
    dataLocation: "Repo files",
    relatedToolIds: [],
  },
  "gm-design-sot": {
    id: "gm-design-sot",
    title: "Design source of truth",
    description: "aixia-global owner files 00–16 — active implementation law.",
    level: 3,
    parentId: "global-memory",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "memory-area",
    currentRuntime: "Repo files",
    targetRuntime: "Living law with approved owner updates",
    sourceType: "internal-app",
    sourcePath: "src/design-system/aixia-global/",
    status: "existing",
    installedStatus: "Present in AiXia-github",
    configuredStatus: "Active law for implementation",
    usedBy: ["All agents", "Guardrails"],
    dataLocation: "Repo files",
    relatedToolIds: [],
  },
  "gm-workflow-rules": {
    id: "gm-workflow-rules",
    title: "Workflow rules",
    description: "AgentOps product specs, daily workflow, and verification rules.",
    level: 3,
    parentId: "global-memory",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "memory-area",
    currentRuntime: "Repo files",
    targetRuntime: "Integrated with AgentOps UI workflows",
    sourceType: "internal-app",
    sourcePath: "qa-agent/agentops/",
    status: "existing",
    installedStatus: "Extensive spec docs",
    configuredStatus: "Some README status lines stale vs code",
    usedBy: ["AgentOps"],
    dataLocation: "Repo files",
    relatedToolIds: [],
  },
  "gm-issue-history": {
    id: "gm-issue-history",
    title: "Issue history",
    description: "AgentOps findings, queue state, and owner feedback history.",
    level: 3,
    parentId: "global-memory",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "memory-area",
    currentRuntime: "Supabase",
    targetRuntime: "Full issue workspace with Hermes context",
    sourceType: "internal-app",
    sourcePath: "agentops_findings",
    status: "partial",
    installedStatus: "Tables and service layer exist when migration applied",
    configuredStatus: "Owner-gated",
    usedBy: ["AgentOps Issues"],
    dataLocation: "Supabase",
    relatedToolIds: [],
  },
  "gm-verified-fixes": {
    id: "gm-verified-fixes",
    title: "Verified fixes",
    description: "Verification outcomes and lesson candidates from resolved issues.",
    level: 3,
    parentId: "global-memory",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "memory-area",
    currentRuntime: "Supabase metadata",
    targetRuntime: "Lesson promotion to memory files after owner approval",
    sourceType: "internal-app",
    status: "partial",
    installedStatus: "Lesson candidate flow in Knowledge page",
    configuredStatus: "Manual approval required",
    usedBy: ["AgentOps Knowledge"],
    dataLocation: "Supabase + owner feedback",
    relatedToolIds: [],
  },
  "gm-tool-registry": {
    id: "gm-tool-registry",
    title: "Tool registry",
    description: "Cursor external registry and this in-app Tools Hub registry.",
    level: 3,
    parentId: "global-memory",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "memory-area",
    currentRuntime: "Repo files",
    targetRuntime: "Unified hub + registry/TOOL_REGISTRY.md alignment",
    sourceType: "internal-app",
    sourcePath: "registry/TOOL_REGISTRY.md",
    status: "partial",
    installedStatus: "External registry exists; in-app hub Phase 1",
    configuredStatus: "No Supabase tool tables",
    usedBy: ["Cursor agents", "Tools Hub"],
    dataLocation: "Repo files",
    relatedToolIds: [],
  },
  "gm-piter-instructions": {
    id: "gm-piter-instructions",
    title: "Piter instructions",
    description: "Owner focus directives, remarks, and explicit scope instructions.",
    level: 3,
    parentId: "global-memory",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "memory-area",
    currentRuntime: "Supabase owner feedback",
    targetRuntime: "Hermes-weighted owner priority recall",
    sourceType: "internal-app",
    status: "partial",
    installedStatus: "Focus directives and owner feedback APIs",
    configuredStatus: "No Hermes writer",
    usedBy: ["AgentOps"],
    dataLocation: "Supabase",
    relatedToolIds: ["hermes"],
  },

  // ─── Level 3: Per-Agent Memory ────────────────────────────────────────────
  "pam-agent-role": {
    id: "pam-agent-role",
    title: "Agent role",
    description: "Synthetic agent role and specialty from manifests.",
    level: 3,
    parentId: "per-agent-memory",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "memory-area",
    currentRuntime: "Repo manifests",
    targetRuntime: "Synced manifest + DB memory",
    sourceType: "internal-app",
    sourcePath: "qa-agent/agents/*/manifest.json",
    status: "existing",
    installedStatus: "12 agent manifests",
    configuredStatus: "Static manifests",
    usedBy: ["AgentOps agents"],
    dataLocation: "Repo files",
    relatedToolIds: [],
  },
  "pam-permissions": {
    id: "pam-permissions",
    title: "Permissions",
    description: "App role and module access expectations per agent.",
    level: 3,
    parentId: "per-agent-memory",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "memory-area",
    currentRuntime: "Registry JSON + manifests",
    targetRuntime: "Aligned with pageAccess and synthetic users",
    sourceType: "internal-app",
    sourcePath: "qa-agent/registry/ai-access-levels.json",
    status: "existing",
    installedStatus: "QA registry files",
    configuredStatus: "Advisory",
    usedBy: ["Browser QA", "Agents"],
    dataLocation: "Repo files",
    relatedToolIds: [],
  },
  "pam-allowed-tools": {
    id: "pam-allowed-tools",
    title: "Allowed tools",
    description: "Which tools each agent may reference (future assignment).",
    level: 3,
    parentId: "per-agent-memory",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "memory-area",
    currentRuntime: "Target only",
    targetRuntime: "Per-agent tool assignment from Tools Hub",
    sourceType: "internal-app",
    status: "target-only",
    installedStatus: "Not built in Phase 1",
    configuredStatus: "Placeholder",
    usedBy: ["Future Tools Hub"],
    dataLocation: "None",
    relatedToolIds: [],
  },
  "pam-module-responsibility": {
    id: "pam-module-responsibility",
    title: "Module responsibility",
    description: "Which website modules each agent audits or owns.",
    level: 3,
    parentId: "per-agent-memory",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "memory-area",
    currentRuntime: "Manifest job.md files",
    targetRuntime: "Control Center module catalog alignment",
    sourceType: "internal-app",
    sourcePath: "qa-agent/agents/*/job.md",
    status: "existing",
    installedStatus: "Per-agent job docs",
    configuredStatus: "Static",
    usedBy: ["Agents"],
    dataLocation: "Repo files",
    relatedToolIds: [],
  },
  "pam-findings-history": {
    id: "pam-findings-history",
    title: "Findings history",
    description: "Issues raised or reviewed by each agent.",
    level: 3,
    parentId: "per-agent-memory",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "memory-area",
    currentRuntime: "Supabase findings",
    targetRuntime: "Agent timeline integration",
    sourceType: "internal-app",
    status: "partial",
    installedStatus: "agent_id on findings",
    configuredStatus: "Timeline UI exists",
    usedBy: ["Agent workspace"],
    dataLocation: "Supabase",
    relatedToolIds: [],
  },
  "pam-current-focus": {
    id: "pam-current-focus",
    title: "Current focus",
    description: "Active focus string per managed agent.",
    level: 3,
    parentId: "per-agent-memory",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "memory-area",
    currentRuntime: "Supabase + UI",
    targetRuntime: "Focus directives drive scan ranking",
    sourceType: "internal-app",
    status: "partial",
    installedStatus: "Agents page focus fields",
    configuredStatus: "Manual owner updates",
    usedBy: ["Agents page"],
    dataLocation: "Supabase",
    relatedToolIds: [],
  },
  "pam-learned-lessons": {
    id: "pam-learned-lessons",
    title: "Learned lessons",
    description: "Approved lesson candidates for agent memory.",
    level: 3,
    parentId: "per-agent-memory",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "memory-area",
    currentRuntime: "Knowledge page drafts",
    targetRuntime: "Exported to agent-memory/*.memory.md",
    sourceType: "internal-app",
    status: "partial",
    installedStatus: "Lesson candidate workflow",
    configuredStatus: "Owner approval required",
    usedBy: ["Knowledge page"],
    dataLocation: "Supabase metadata",
    relatedToolIds: [],
  },

  // ─── Level 3: Memory & Coordination Tools ─────────────────────────────────
  "mct-hermes": {
    id: "mct-hermes",
    title: "Hermes",
    description: "Advisory QA memory and issue clarification adapter (staging-only design).",
    level: 3,
    parentId: "memory-coordination-tools",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Mock fallback default",
    targetRuntime: "Staging Hermes via /api/agentops/hermes",
    sourceType: "internal-app",
    sourcePath: "src/lib/agentops/hermesAdapter.ts",
    sourceUrl: "qa-agent/hermes/",
    status: "needs-setup",
    installedStatus: "Contracts and handler exist",
    configuredStatus: "hermesActive false in readiness constants",
    usedBy: ["Issue Workspace"],
    dataLocation: "qa-agent/hermes/",
    relatedToolIds: ["hermes"],
    notes: "8/100 readiness per AgentOps README; not app-callable by default.",
    route: `${TOOLS_HUB_BASE_PATH}/agent-brain-memory/memory-coordination-tools/hermes`,
  },
  "mct-agentmemory": {
    id: "mct-agentmemory",
    title: "AgentMemory",
    description: "External persistent memory for coding agents (npx planned).",
    level: 3,
    parentId: "memory-coordination-tools",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Not installed",
    targetRuntime: "npx @agentmemory/agentmemory staging recall",
    sourceType: "github-repo",
    sourceUrl: "https://github.com/rohitg00/agentmemory",
    status: "not-installed",
    installedStatus: "No ../tools/agentmemory/ clone",
    configuredStatus: "Registry experimental planned",
    usedBy: ["Planned Hermes integration"],
    dataLocation: "qa-agent/hermes/.agentmemory-local/ (empty)",
    relatedToolIds: ["agentmemory"],
  },

  // ─── Level 3: Code / Context Understanding ────────────────────────────────
  "ccu-codegraph": {
    id: "ccu-codegraph",
    title: "CodeGraph",
    description: "AST knowledge graph via Cursor MCP; app discovery mock only.",
    level: 3,
    parentId: "code-context-understanding",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Cursor MCP local",
    targetRuntime: "Read-only sanitized artifact for Issue Workspace",
    sourceType: "mcp",
    sourcePath: ".cursor/mcp.json",
    status: "partial",
    installedStatus: ".codegraph/ index present (untracked)",
    configuredStatus: "CODEGRAPH_RUNTIME_ACTIVE false in app",
    usedBy: ["Cursor agents", "Issue Workspace hints"],
    dataLocation: ".codegraph/",
    relatedToolIds: ["codegraph"],
  },
  "ccu-understand-anything": {
    id: "ccu-understand-anything",
    title: "Understand-Anything",
    description: "Interactive codebase knowledge graph plugin (Lum1104 fork cloned).",
    level: 3,
    parentId: "code-context-understanding",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Local clone only",
    targetRuntime: "Architecture maps to repo-analysis/",
    sourceType: "github-repo",
    sourcePath: "../tools/understand-anything/",
    sourceUrl: "https://github.com/Lum1104/Understand-Anything.git",
    status: "cloned-only",
    installedStatus: "Cloned; no node_modules",
    configuredStatus: "Needs pnpm install and plugin setup",
    usedBy: ["Cursor (planned)"],
    dataLocation: "Project .understand-anything/ when run",
    relatedToolIds: ["understand-anything"],
  },
  "ccu-claude-context": {
    id: "ccu-claude-context",
    title: "claude-context",
    description: "Semantic code search MCP (Zilliz vector DB + embeddings).",
    level: 3,
    parentId: "code-context-understanding",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Local clone only",
    targetRuntime: "MCP npx when keys configured",
    sourceType: "github-repo",
    sourcePath: "../tools/claude-context/",
    sourceUrl: "https://github.com/zilliztech/claude-context.git",
    status: "cloned-only",
    installedStatus: "Cloned; no node_modules",
    configuredStatus: "Not in AiXia .cursor/mcp.json",
    usedBy: ["Planned when CodeGraph insufficient"],
    dataLocation: "Cloud vector DB (Zilliz) when active",
    relatedToolIds: ["claude-context"],
  },

  // ─── Level 3: Evidence Tools ──────────────────────────────────────────────
  "et-browser-qa": {
    id: "et-browser-qa",
    title: "Browser QA",
    description: "qa-agent browser runners and safe workflow specs.",
    level: 3,
    parentId: "evidence-tools",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Local scripts",
    targetRuntime: "Owner-triggered staging runs",
    sourceType: "internal-app",
    sourcePath: "qa-agent/scripts/agentops-browser-qa-runner.mjs",
    status: "partial",
    installedStatus: "Scripts in package.json",
    configuredStatus: "Manual execution",
    usedBy: ["Automation page", "Orchestrator"],
    dataLocation: "qa-agent/reports/browser-qa/",
    relatedToolIds: ["browser-qa"],
  },
  "et-playwright": {
    id: "et-playwright",
    title: "Playwright",
    description: "Browser automation test runner for AgentOps smokes.",
    level: 3,
    parentId: "evidence-tools",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Local dev dependency",
    targetRuntime: "CI smoke when GitHub Actions added",
    sourceType: "npm-package",
    sourcePath: "qa-agent/browser-qa/playwright.config.mjs",
    status: "existing",
    installedStatus: "@playwright/test in package.json",
    configuredStatus: "qa:agentops-browser-smoke script",
    usedBy: ["QA smokes"],
    dataLocation: "qa-agent/reports/browser-qa/",
    relatedToolIds: ["playwright"],
  },
  "et-reports": {
    id: "et-reports",
    title: "reports",
    description: "Generated QA, orchestrator, and verification report artifacts.",
    level: 3,
    parentId: "evidence-tools",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Local files when generated",
    targetRuntime: "Import plans into AgentOps findings",
    sourceType: "internal-app",
    sourcePath: "qa-agent/reports/",
    status: "partial",
    installedStatus: "Paths referenced; folder often empty",
    configuredStatus: "Gitignored outputs",
    usedBy: ["Import operators"],
    dataLocation: "Local files",
    relatedToolIds: [],
  },
  "et-guardrails": {
    id: "et-guardrails",
    title: "guardrails",
    description: "Build-time and QA static design guardrails.",
    level: 3,
    parentId: "evidence-tools",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "tool",
    currentRuntime: "npm run build gate",
    targetRuntime: "G-08 table parity enforcement complete",
    sourceType: "internal-app",
    sourcePath: "scripts/aixia-guardrails.mjs",
    status: "existing",
    installedStatus: "Runs on build",
    configuredStatus: "Policy in aixia-global/15",
    usedBy: ["Build", "QA static scan"],
    dataLocation: "None",
    relatedToolIds: ["aixia-guardrails"],
  },
  "et-verification-results": {
    id: "et-verification-results",
    title: "verification results",
    description: "Manual and script-recorded verification outcomes.",
    level: 3,
    parentId: "evidence-tools",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Supabase verifications",
    targetRuntime: "Linked to fix plans and browser re-test",
    sourceType: "internal-app",
    sourcePath: "agentops_verifications",
    status: "partial",
    installedStatus: "Verification UI and runner script",
    configuredStatus: "Owner manual first",
    usedBy: ["Advanced", "Issues"],
    dataLocation: "Supabase",
    relatedToolIds: [],
  },

  // ─── Level 3: Reasoning Layer ─────────────────────────────────────────────
  "rl-cursor": {
    id: "rl-cursor",
    title: "Cursor",
    description: "Primary builder IDE and agent router for AiXia implementation.",
    level: 3,
    parentId: "reasoning-layer",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Local Computer",
    targetRuntime: "Cursor handoffs from AgentOps fix plans",
    sourceType: "external-provider",
    status: "existing",
    installedStatus: "Workspace AiXia-github",
    configuredStatus: "Manual copy prompts; no auto-trigger",
    usedBy: ["Piter", "Build agents"],
    dataLocation: "None",
    relatedToolIds: [],
  },
  "rl-smart-cloud-llm": {
    id: "rl-smart-cloud-llm",
    title: "smart cloud LLM",
    description: "Cloud models via product AI router (not AgentOps default).",
    level: 3,
    parentId: "reasoning-layer",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Cloud",
    targetRuntime: "Optional advisory for non-AgentOps surfaces",
    sourceType: "external-provider",
    sourcePath: "src/lib/ai/aiRouter.ts",
    status: "partial",
    installedStatus: "FloatingAIChat / ai-management",
    configuredStatus: "Separate from AgentOps mock default",
    usedBy: ["AI Management", "Chat"],
    dataLocation: "Supabase AI settings",
    relatedToolIds: [],
  },
  "rl-strong-local-llm-later": {
    id: "rl-strong-local-llm-later",
    title: "strong local LLM later",
    description: "Higher-capacity local models (e.g. qwen3:14b) when Ollama ready.",
    level: 3,
    parentId: "reasoning-layer",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Target only",
    targetRuntime: "Ollama with owner-approved models",
    sourceType: "local-installed-tool",
    status: "target-only",
    installedStatus: "pull script exists; not verified run",
    configuredStatus: "scripts/pull-agentops-ollama-models.ps1",
    usedBy: ["Planned Council/Issue chat"],
    dataLocation: "Local Ollama",
    relatedToolIds: ["local-llm"],
  },
  "rl-task-specific-model": {
    id: "rl-task-specific-model",
    title: "task-specific reasoning model",
    description: "Purpose-tuned models per task type (verification, design, etc.).",
    level: 3,
    parentId: "reasoning-layer",
    categoryId: "agent-brain-memory",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Planned",
    targetRuntime: "Per-task routing with owner gates",
    sourceType: "planned",
    status: "planned",
    installedStatus: "Not implemented",
    configuredStatus: "Architecture docs only",
    usedBy: ["Future AgentOps"],
    dataLocation: "None",
    relatedToolIds: [],
  },

  // ─── Level 2: Chat & Voice ──────────────────────────────────────────────────
  "chat-local-llm": {
    id: "chat-local-llm",
    title: "Local LLM",
    description: "Ollama-backed AgentOps chat via server proxy.",
    level: 2,
    parentId: "chat-voice",
    categoryId: "chat-voice",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Hybrid — VITE + /api/agentops/llm",
    targetRuntime: "Staging Ollama with probe health",
    sourceType: "internal-app",
    sourcePath: "src/lib/agentops/localLlmAdapter.ts",
    status: "partial",
    installedStatus: "Adapter and API routes exist",
    configuredStatus: "Env-gated; mock fallback available",
    usedBy: ["Council", "Agents", "Issues"],
    dataLocation: "Session metadata in Supabase",
    relatedToolIds: ["local-llm"],
    route: `${TOOLS_HUB_BASE_PATH}/chat-voice`,
  },
  "chat-stt": {
    id: "chat-stt",
    title: "STT",
    description: "Speech-to-text for voice chat modes.",
    level: 2,
    parentId: "chat-voice",
    categoryId: "chat-voice",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Product voice stack",
    targetRuntime: "AgentOps voice phase",
    sourceType: "internal-app",
    sourcePath: "src/lib/ai/voice.ts",
    status: "planned",
    installedStatus: "FloatingAIChat voice modes",
    configuredStatus: "Not AgentOps-connected",
    usedBy: ["AI chat"],
    dataLocation: "Unknown",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/chat-voice`,
  },
  "chat-tts": {
    id: "chat-tts",
    title: "TTS",
    description: "Text-to-speech output for assistant replies.",
    level: 2,
    parentId: "chat-voice",
    categoryId: "chat-voice",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Product voice stack",
    targetRuntime: "Supertonic or cloud TTS when approved",
    sourceType: "internal-app",
    status: "planned",
    installedStatus: "Voice page in ai-management",
    configuredStatus: "Deferred per local-llm-tool-evaluation",
    usedBy: ["AI Management"],
    dataLocation: "Unknown",
    relatedToolIds: ["supertonic"],
    route: `${TOOLS_HUB_BASE_PATH}/chat-voice`,
  },
  "chat-supertonic": {
    id: "chat-supertonic",
    title: "Supertonic",
    description: "On-device TTS from supertone-inc (not cloned in tools/).",
    level: 2,
    parentId: "chat-voice",
    categoryId: "chat-voice",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Not installed",
    targetRuntime: "Local on-device TTS",
    sourceType: "github-repo",
    sourceUrl: "https://github.com/supertone-inc/supertonic",
    status: "not-installed",
    installedStatus: "Not in ../tools/",
    configuredStatus: "Documented as defer",
    usedBy: ["Future voice phase"],
    dataLocation: "None",
    relatedToolIds: ["supertonic"],
    route: `${TOOLS_HUB_BASE_PATH}/chat-voice`,
  },
  "chat-avatar-later": {
    id: "chat-avatar-later",
    title: "Avatar later",
    description: "Avatar pack runtime and Mediapipe assets for face-to-face chat.",
    level: 2,
    parentId: "chat-voice",
    categoryId: "chat-voice",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Partial in FloatingAIChat",
    targetRuntime: "Unified avatar/voice studio",
    sourceType: "internal-app",
    sourcePath: "src/components/ai/FloatingAIChat.tsx",
    status: "partial",
    installedStatus: "Mediapipe wasm in public/",
    configuredStatus: "Not Tools Hub runtime",
    usedBy: ["Product chat"],
    dataLocation: "Repo assets",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/chat-voice`,
  },

  // ─── Level 2: Website QA & Evidence ───────────────────────────────────────
  "qa-browser-runner": {
    id: "qa-browser-runner",
    title: "Browser QA runner",
    description: "agentops-browser-qa-runner and related npm scripts.",
    level: 2,
    parentId: "website-qa-evidence",
    categoryId: "website-qa-evidence",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Local Computer",
    targetRuntime: "Orchestrated staging runs",
    sourceType: "internal-app",
    sourcePath: "qa-agent/scripts/agentops-browser-qa-runner.mjs",
    status: "partial",
    installedStatus: "Script exists",
    configuredStatus: "Manual trigger",
    usedBy: ["qa:agentops-browser-foundation"],
    dataLocation: "qa-agent/reports/browser-qa/",
    relatedToolIds: ["browser-qa"],
    route: `${TOOLS_HUB_BASE_PATH}/website-qa-evidence`,
  },
  "qa-playwright-runner": {
    id: "qa-playwright-runner",
    title: "Playwright cloud/local runner",
    description: "Playwright test config and smoke specs.",
    level: 2,
    parentId: "website-qa-evidence",
    categoryId: "website-qa-evidence",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Local Computer",
    targetRuntime: "Optional cloud CI runner",
    sourceType: "npm-package",
    sourcePath: "qa-agent/browser-qa/",
    status: "partial",
    installedStatus: "17 spec files; dep in package.json",
    configuredStatus: "AGENTOPS_QA_BASE_URL env for target",
    usedBy: ["qa:agentops-browser-smoke"],
    dataLocation: "qa-agent/reports/browser-qa/",
    relatedToolIds: ["playwright"],
    route: `${TOOLS_HUB_BASE_PATH}/website-qa-evidence`,
  },
  "qa-crawler": {
    id: "qa-crawler",
    title: "crawler",
    description: "Static route discovery (not a live web crawler).",
    level: 2,
    parentId: "website-qa-evidence",
    categoryId: "website-qa-evidence",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Local script",
    targetRuntime: "Expanded discovery for AgentOps scans",
    sourceType: "internal-app",
    sourcePath: "qa-agent/scripts/static-app-discovery.mjs",
    status: "existing",
    installedStatus: "qa:static-discovery",
    configuredStatus: "Read-only scan",
    usedBy: ["Orchestrator"],
    dataLocation: "qa-agent/reports/static-app-discovery.json",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/website-qa-evidence`,
    notes: "No separate crawler service found in audits.",
  },
  "qa-visual-qa": {
    id: "qa-visual-qa",
    title: "visual QA",
    description: "Playwright screenshots and visual parity guardrails.",
    level: 2,
    parentId: "website-qa-evidence",
    categoryId: "website-qa-evidence",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Local scripts",
    targetRuntime: "Screenshot review in import plans",
    sourceType: "internal-app",
    sourcePath: "scripts/guardrails/aixia-visual-parity.mjs",
    status: "partial",
    installedStatus: "Screenshot paths in smoke reports",
    configuredStatus: "Warn-only visual parity in build",
    usedBy: ["Guardrails", "Browser QA"],
    dataLocation: "qa-agent/reports/browser-qa/screenshots/",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/website-qa-evidence`,
  },
  "qa-reports-storage": {
    id: "qa-reports-storage",
    title: "reports storage",
    description: "Filesystem report outputs from QA and orchestrator.",
    level: 2,
    parentId: "website-qa-evidence",
    categoryId: "website-qa-evidence",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Local files",
    targetRuntime: "Hub visibility of last run metadata",
    sourceType: "internal-app",
    sourcePath: "qa-agent/reports/",
    status: "partial",
    installedStatus: "Directory structure referenced",
    configuredStatus: "Often empty until runs",
    usedBy: ["Import pipelines"],
    dataLocation: "Local files",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/website-qa-evidence`,
  },
  "qa-verification-runner": {
    id: "qa-verification-runner",
    title: "verification runner",
    description: "agentops-verification-runner dry-run and apply modes.",
    level: 2,
    parentId: "website-qa-evidence",
    categoryId: "website-qa-evidence",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Local script",
    targetRuntime: "Owner-approved apply only",
    sourceType: "internal-app",
    sourcePath: "qa-agent/scripts/agentops-verification-runner.mjs",
    status: "partial",
    installedStatus: "qa:agentops-verify script",
    configuredStatus: "Dry-run default in orchestrator",
    usedBy: ["Automation", "Advanced"],
    dataLocation: "qa-agent/reports/verification/",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/website-qa-evidence`,
  },

  // ─── Level 2: Build & Development ─────────────────────────────────────────
  "build-cursor": {
    id: "build-cursor",
    title: "Cursor",
    description: "IDE workspace, rules, and MCP for AiXia-github.",
    level: 2,
    parentId: "build-development",
    categoryId: "build-development",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Local Computer",
    targetRuntime: "Registry-logged tool selection each session",
    sourceType: "external-provider",
    sourcePath: ".cursor/",
    status: "existing",
    installedStatus: "Rules and mcp.json present",
    configuredStatus: "codegraph + supabase + vercel MCP",
    usedBy: ["All build agents"],
    dataLocation: "Repo files",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/build-development`,
  },
  "build-github-tools": {
    id: "build-github-tools",
    title: "GitHub tools",
    description: "Git remote, gh CLI workflows (Actions not in repo).",
    level: 2,
    parentId: "build-development",
    categoryId: "build-development",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Cloud",
    targetRuntime: "GitHub Actions CI for QA smokes",
    sourceType: "github-repo",
    sourceUrl: "https://github.com/piterdrori/AiXia.git",
    status: "partial",
    installedStatus: "Git repo; no .github/workflows found",
    configuredStatus: "Manual PR workflow",
    usedBy: ["Piter"],
    dataLocation: "GitHub",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/build-development`,
  },
  "build-supabase-mcp": {
    id: "build-supabase-mcp",
    title: "Supabase MCP",
    description: "Schema and migration advisory via MCP.",
    level: 2,
    parentId: "build-development",
    categoryId: "build-development",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Cloud MCP",
    targetRuntime: "Read-only advisory unless Piter approves migrations",
    sourceType: "mcp",
    sourcePath: ".cursor/mcp.json",
    sourceUrl: "https://mcp.supabase.com/mcp",
    status: "partial",
    installedStatus: "MCP configured",
    configuredStatus: "No auto-apply migrations",
    usedBy: ["Cursor agents"],
    dataLocation: "Supabase",
    relatedToolIds: ["supabase-mcp"],
    route: `${TOOLS_HUB_BASE_PATH}/build-development`,
  },
  "build-vercel-mcp": {
    id: "build-vercel-mcp",
    title: "Vercel MCP",
    description: "Deploy and project linkage advisory.",
    level: 2,
    parentId: "build-development",
    categoryId: "build-development",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Cloud MCP",
    targetRuntime: "Deploy pipeline visibility in Hub",
    sourceType: "mcp",
    sourcePath: ".cursor/mcp.json",
    sourceUrl: "https://mcp.vercel.com",
    status: "partial",
    installedStatus: "MCP configured",
    configuredStatus: "No auto-deploy from agents",
    usedBy: ["Cursor agents"],
    dataLocation: "Cloud",
    relatedToolIds: ["vercel-mcp"],
    route: `${TOOLS_HUB_BASE_PATH}/build-development`,
  },
  "build-codegraph-mcp": {
    id: "build-codegraph-mcp",
    title: "CodeGraph MCP",
    description: "Structural code intelligence for Cursor.",
    level: 2,
    parentId: "build-development",
    categoryId: "build-development",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Local MCP + .codegraph/",
    targetRuntime: "Primary symbol/impact queries for agents",
    sourceType: "mcp",
    sourcePath: ".cursor/mcp.json",
    status: "partial",
    installedStatus: "MCP + index files present",
    configuredStatus: "Read-only index",
    usedBy: ["Cursor agents"],
    dataLocation: ".codegraph/",
    relatedToolIds: ["codegraph"],
    route: `${TOOLS_HUB_BASE_PATH}/build-development`,
  },
  "build-local-scripts": {
    id: "build-local-scripts",
    title: "local build scripts",
    description: "aixia-guardrails, build, and qa:* npm scripts.",
    level: 2,
    parentId: "build-development",
    categoryId: "build-development",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Local Computer",
    targetRuntime: "CI parity with local scripts",
    sourceType: "internal-app",
    sourcePath: "package.json",
    status: "existing",
    installedStatus: "npm run build runs guardrails",
    configuredStatus: "Many qa:agentops-* scripts",
    usedBy: ["Build", "QA"],
    dataLocation: "None",
    relatedToolIds: ["aixia-guardrails"],
    route: `${TOOLS_HUB_BASE_PATH}/build-development`,
  },

  // ─── Level 2: Design Crew & References ────────────────────────────────────
  "design-shadcn-admin": {
    id: "design-shadcn-admin",
    title: "shadcn-admin",
    description: "Admin dashboard reference (satnaing/shadcn-admin).",
    level: 2,
    parentId: "design-crew-references",
    categoryId: "design-crew-references",
    childrenIds: [],
    type: "reference",
    currentRuntime: "Local clone ../reference/",
    targetRuntime: "Read-only pattern comparison",
    sourceType: "github-repo",
    sourcePath: "../reference/shadcn-admin/",
    sourceUrl: "https://github.com/satnaing/shadcn-admin.git",
    status: "cloned-only",
    installedStatus: "Cloned; no node_modules",
    configuredStatus: "registry reference-only",
    usedBy: ["Design tasks"],
    dataLocation: "Sibling repo",
    relatedToolIds: ["shadcn-admin"],
    route: `${TOOLS_HUB_BASE_PATH}/design-crew-references`,
  },
  "design-tailadmin-react": {
    id: "design-tailadmin-react",
    title: "TailAdmin React",
    description: "React Tailwind admin dashboard reference.",
    level: 2,
    parentId: "design-crew-references",
    categoryId: "design-crew-references",
    childrenIds: [],
    type: "reference",
    currentRuntime: "Local clone ../reference/",
    targetRuntime: "Read-only layout comparison",
    sourceType: "github-repo",
    sourcePath: "../reference/free-react-tailwind-admin-dashboard/",
    sourceUrl: "https://github.com/TailAdmin/free-react-tailwind-admin-dashboard.git",
    status: "cloned-only",
    installedStatus: "Cloned; no node_modules",
    configuredStatus: "registry reference-only",
    usedBy: ["Design tasks"],
    dataLocation: "Sibling repo",
    relatedToolIds: ["tailadmin-react"],
    route: `${TOOLS_HUB_BASE_PATH}/design-crew-references`,
  },
  "design-tailadmin-multi": {
    id: "design-tailadmin-multi",
    title: "TailAdmin multi-template",
    description: "Multi-framework TailAdmin template reference.",
    level: 2,
    parentId: "design-crew-references",
    categoryId: "design-crew-references",
    childrenIds: [],
    type: "reference",
    currentRuntime: "Local clone ../reference/",
    targetRuntime: "Comparison only — prefer React variant",
    sourceType: "github-repo",
    sourcePath: "../reference/free-tailwind-admin-dashboard-template/",
    sourceUrl: "https://github.com/Tailwind-Admin/free-tailwind-admin-dashboard-template.git",
    status: "cloned-only",
    installedStatus: "Cloned; no node_modules",
    configuredStatus: "Do not copy non-React variants into AiXia",
    usedBy: ["Design tasks"],
    dataLocation: "Sibling repo",
    relatedToolIds: ["tailadmin-multi"],
    route: `${TOOLS_HUB_BASE_PATH}/design-crew-references`,
  },
  "design-aixia-global-sot": {
    id: "design-aixia-global-sot",
    title: "AiXia global source of truth",
    description: "aixia-global owner files — active design law.",
    level: 2,
    parentId: "design-crew-references",
    categoryId: "design-crew-references",
    childrenIds: [],
    type: "reference",
    currentRuntime: "Inside AiXia App repo",
    targetRuntime: "Living law with approved updates",
    sourceType: "internal-app",
    sourcePath: "src/design-system/aixia-global/",
    status: "existing",
    installedStatus: "00–16 owner files",
    configuredStatus: "Guardrails enforce",
    usedBy: ["All implementation"],
    dataLocation: "Repo files",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/design-crew-references`,
  },
  "design-visual-qa-rules": {
    id: "design-visual-qa-rules",
    title: "visual/design QA rules",
    description: "Static design guardrails and visual parity checks.",
    level: 2,
    parentId: "design-crew-references",
    categoryId: "design-crew-references",
    childrenIds: [],
    type: "reference",
    currentRuntime: "Local scripts",
    targetRuntime: "Browser + static parity in CI",
    sourceType: "internal-app",
    sourcePath: "src/design-system/aixia-global/15-guardrail-rules.md",
    status: "existing",
    installedStatus: "qa:static-design-guardrails mirror",
    configuredStatus: "Build gate + QA reports",
    usedBy: ["Guardrails"],
    dataLocation: "Repo files",
    relatedToolIds: ["aixia-guardrails"],
    route: `${TOOLS_HUB_BASE_PATH}/design-crew-references`,
  },

  // ─── Level 2: Automation & Integrations ───────────────────────────────────
  "auto-zapier": {
    id: "auto-zapier",
    title: "Zapier",
    description: "Future MCP action bridge — blocked in registry.",
    level: 2,
    parentId: "automation-integrations",
    categoryId: "automation-integrations",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Not installed",
    targetRuntime: "Owner-approved external actions only",
    sourceType: "planned",
    sourcePath: "registry/TOOL_REGISTRY.md",
    status: "planned",
    installedStatus: "Not cloned",
    configuredStatus: "Blocked until security approval",
    usedBy: ["None"],
    dataLocation: "None",
    relatedToolIds: ["zapier-mcp"],
    route: `${TOOLS_HUB_BASE_PATH}/automation-integrations`,
  },
  "auto-webhooks": {
    id: "auto-webhooks",
    title: "webhooks",
    description: "Inbound/outbound webhook connectors (not built).",
    level: 2,
    parentId: "automation-integrations",
    categoryId: "automation-integrations",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Planned",
    targetRuntime: "Staging webhooks with auth",
    sourceType: "planned",
    status: "planned",
    installedStatus: "Not implemented",
    configuredStatus: "Placeholder",
    usedBy: ["Future"],
    dataLocation: "None",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/automation-integrations`,
  },
  "auto-api-connectors": {
    id: "auto-api-connectors",
    title: "API connectors",
    description: "Generic API integration layer for AgentOps.",
    level: 2,
    parentId: "automation-integrations",
    categoryId: "automation-integrations",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Planned",
    targetRuntime: "Registry-driven connector catalog",
    sourceType: "planned",
    status: "planned",
    installedStatus: "Not implemented",
    configuredStatus: "Placeholder",
    usedBy: ["Future"],
    dataLocation: "None",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/automation-integrations`,
  },
  "auto-notifications": {
    id: "auto-notifications",
    title: "notification tools",
    description: "Owner notification channels for AgentOps events.",
    level: 2,
    parentId: "automation-integrations",
    categoryId: "automation-integrations",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Planned",
    targetRuntime: "Optional email/push on queue health",
    sourceType: "planned",
    status: "planned",
    installedStatus: "Not implemented",
    configuredStatus: "Placeholder",
    usedBy: ["Future"],
    dataLocation: "None",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/automation-integrations`,
  },
  "auto-github-actions-later": {
    id: "auto-github-actions-later",
    title: "GitHub Actions later",
    description: "CI workflows for build and QA smokes.",
    level: 2,
    parentId: "automation-integrations",
    categoryId: "automation-integrations",
    childrenIds: [],
    type: "tool",
    currentRuntime: "Not installed",
    targetRuntime: "PR checks running qa:agentops-* subset",
    sourceType: "planned",
    status: "not-installed",
    installedStatus: "No .github/workflows in repo",
    configuredStatus: "Target only",
    usedBy: ["Future CI"],
    dataLocation: "GitHub",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/automation-integrations`,
  },

  // ─── Level 2: Runtime & Platform ──────────────────────────────────────────
  "runtime-supabase": {
    id: "runtime-supabase",
    title: "Supabase",
    description: "Database, auth, storage, and RLS for AiXia.",
    level: 2,
    parentId: "runtime-platform",
    categoryId: "runtime-platform",
    childrenIds: [],
    type: "runtime-service",
    currentRuntime: "Cloud Supabase",
    targetRuntime: "Staging + production projects",
    sourceType: "external-provider",
    sourcePath: "supabase/",
    status: "existing",
    installedStatus: "Migrations and client in repo",
    configuredStatus: "AgentOps tables in migration file",
    usedBy: ["AiXia app", "AgentOps"],
    dataLocation: "Supabase",
    relatedToolIds: ["supabase-mcp"],
    route: `${TOOLS_HUB_BASE_PATH}/runtime-platform`,
  },
  "runtime-vercel": {
    id: "runtime-vercel",
    title: "Vercel",
    description: "Frontend hosting and preview deployments.",
    level: 2,
    parentId: "runtime-platform",
    categoryId: "runtime-platform",
    childrenIds: [],
    type: "runtime-service",
    currentRuntime: "Cloud",
    targetRuntime: "Staging previews for AgentOps QA",
    sourceType: "external-provider",
    status: "partial",
    installedStatus: "MCP configured",
    configuredStatus: "Deploy requires Piter approval",
    usedBy: ["AiXia app"],
    dataLocation: "Cloud",
    relatedToolIds: ["vercel-mcp"],
    route: `${TOOLS_HUB_BASE_PATH}/runtime-platform`,
  },
  "runtime-auth": {
    id: "runtime-auth",
    title: "Auth",
    description: "Supabase auth and profile-gated routes.",
    level: 2,
    parentId: "runtime-platform",
    categoryId: "runtime-platform",
    childrenIds: [],
    type: "runtime-service",
    currentRuntime: "Supabase Auth",
    targetRuntime: "Stable session + agentops_is_owner gate",
    sourceType: "internal-app",
    sourcePath: "src/App.tsx",
    status: "existing",
    installedStatus: "ProtectedRoute wrapper",
    configuredStatus: "Owner allowlist separate from admin",
    usedBy: ["All app routes"],
    dataLocation: "Supabase",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/runtime-platform`,
  },
  "runtime-database": {
    id: "runtime-database",
    title: "Database",
    description: "Postgres tables including agentops_* schema.",
    level: 2,
    parentId: "runtime-platform",
    categoryId: "runtime-platform",
    childrenIds: [],
    type: "runtime-service",
    currentRuntime: "Supabase Postgres",
    targetRuntime: "Applied staging migration",
    sourceType: "internal-app",
    sourcePath: "supabase/migrations/",
    status: "partial",
    installedStatus: "Migration file exists",
    configuredStatus: "Apply status unknown without live check",
    usedBy: ["AgentOps service"],
    dataLocation: "Supabase",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/runtime-platform`,
  },
  "runtime-storage": {
    id: "runtime-storage",
    title: "Storage",
    description: "Supabase storage buckets for uploads and assets.",
    level: 2,
    parentId: "runtime-platform",
    categoryId: "runtime-platform",
    childrenIds: [],
    type: "runtime-service",
    currentRuntime: "Supabase",
    targetRuntime: "Evidence file storage for AgentOps",
    sourceType: "internal-app",
    status: "partial",
    installedStatus: "Used by finance/docs modules",
    configuredStatus: "agentops_evidence_files paths",
    usedBy: ["AiXia modules"],
    dataLocation: "Supabase Storage",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/runtime-platform`,
  },
  "runtime-realtime": {
    id: "runtime-realtime",
    title: "Realtime",
    description: "Supabase realtime subscriptions in product modules.",
    level: 2,
    parentId: "runtime-platform",
    categoryId: "runtime-platform",
    childrenIds: [],
    type: "runtime-service",
    currentRuntime: "Supabase Realtime",
    targetRuntime: "Silent refresh per aixia refresh rules",
    sourceType: "internal-app",
    status: "existing",
    installedStatus: "Used in app modules",
    configuredStatus: "Not AgentOps Tools concern yet",
    usedBy: ["Product modules"],
    dataLocation: "Supabase",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/runtime-platform`,
  },
  "runtime-edge-functions": {
    id: "runtime-edge-functions",
    title: "Edge functions",
    description: "Vercel/serverless API routes including agentops.",
    level: 2,
    parentId: "runtime-platform",
    categoryId: "runtime-platform",
    childrenIds: [],
    type: "runtime-service",
    currentRuntime: "Hybrid api/ folder",
    targetRuntime: "Hermes/LLM proxies on staging",
    sourceType: "internal-app",
    sourcePath: "api/agentops/",
    status: "partial",
    installedStatus: "hermesHandler, llmHandler exist",
    configuredStatus: "Env-gated runtime",
    usedBy: ["AgentOps adapters"],
    dataLocation: "Cloud",
    relatedToolIds: ["hermes", "local-llm"],
    route: `${TOOLS_HUB_BASE_PATH}/runtime-platform`,
  },
  "runtime-background-workers": {
    id: "runtime-background-workers",
    title: "background workers",
    description: "Future schedulers and async job workers.",
    level: 2,
    parentId: "runtime-platform",
    categoryId: "runtime-platform",
    childrenIds: [],
    type: "runtime-service",
    currentRuntime: "Planned",
    targetRuntime: "Owner-approved scheduler only",
    sourceType: "planned",
    sourcePath: "qa-agent/scheduler/",
    status: "planned",
    installedStatus: "Preparation docs only",
    configuredStatus: "neverAutoRun in orchestrator",
    usedBy: ["Future AgentOps"],
    dataLocation: "None",
    relatedToolIds: [],
    route: `${TOOLS_HUB_BASE_PATH}/runtime-platform`,
  },
};

export const TOOL_REGISTRY_MAIN_CATEGORY_IDS: string[] = [
  "agent-brain-memory",
  "chat-voice",
  "website-qa-evidence",
  "build-development",
  "design-crew-references",
  "automation-integrations",
  "runtime-platform",
];

/** Add/remove tools here. Do not hardcode Tools Hub cards inside page JSX. */
export const AGENTOPS_TOOL_REGISTRY = TOOL_REGISTRY_ENTRIES;

export function getToolRegistryEntry(id: string): ToolRegistryEntry | null {
  return AGENTOPS_TOOL_REGISTRY[id] ?? null;
}

export function getToolRegistryMainCategories(): ToolRegistryEntry[] {
  return TOOL_REGISTRY_MAIN_CATEGORY_IDS.map((id) => AGENTOPS_TOOL_REGISTRY[id]).filter(
    Boolean,
  );
}

export function getToolRegistryChildren(parentId: string): ToolRegistryEntry[] {
  const parent = AGENTOPS_TOOL_REGISTRY[parentId];
  if (!parent) return [];
  return parent.childrenIds
    .map((id) => AGENTOPS_TOOL_REGISTRY[id])
    .filter(Boolean);
}

/** Level-2 groups hidden from Agent Brain & Memory hub grid — Hermes owns those layer cards. Routes stay valid. */
export const AGENT_BRAIN_HUB_HIDDEN_GROUP_IDS = ["global-memory", "per-agent-memory"] as const;

/** Category hub cards — filters Hermes-owned foundations from the parent grid. */
export function getToolRegistryCategoryHubGroups(categoryId: string): ToolRegistryEntry[] {
  const groups = getToolRegistryChildren(categoryId);
  if (categoryId !== "agent-brain-memory") return groups;
  const hidden = new Set<string>(AGENT_BRAIN_HUB_HIDDEN_GROUP_IDS);
  return groups.filter((group) => !hidden.has(group.id));
}

export function getToolRegistryCategoryBySlug(
  categorySlug: string,
): ToolRegistryEntry | null {
  const entry = AGENTOPS_TOOL_REGISTRY[categorySlug];
  if (!entry || entry.level !== 1) return null;
  return entry;
}

export function getToolRegistryGroupInCategory(
  categorySlug: string,
  groupSlug: string,
): ToolRegistryEntry | null {
  const entry = AGENTOPS_TOOL_REGISTRY[groupSlug];
  if (!entry || entry.level !== 2 || entry.categoryId !== categorySlug) return null;
  return entry;
}

export function formatToolRegistryStatus(status: ToolRegistryStatus): string {
  return status
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

export function summarizeChildStatuses(childIds: string[]): string {
  if (childIds.length === 0) return "No children";

  const counts = new Map<ToolRegistryStatus, number>();
  for (const id of childIds) {
    const child = AGENTOPS_TOOL_REGISTRY[id];
    if (!child) continue;
    counts.set(child.status, (counts.get(child.status) ?? 0) + 1);
  }

  const parts = [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([status, count]) => `${formatToolRegistryStatus(status)} ${count}`);

  return parts.join(" · ");
}

export function getToolRegistryCategoryRoute(categoryId: string): string {
  return `${TOOLS_HUB_BASE_PATH}/${categoryId}`;
}

export function getToolRegistryGroupRoute(
  categoryId: string,
  groupId: string,
): string {
  return `${TOOLS_HUB_BASE_PATH}/${categoryId}/${groupId}`;
}

/** Resolve a Level 3 tool by URL segment (e.g. `hermes` → `mct-hermes`). */
export function getToolRegistryToolBySlug(
  categoryId: string,
  groupId: string,
  toolSlug: string,
): ToolRegistryEntry | null {
  const group = getToolRegistryGroupInCategory(categoryId, groupId);
  if (!group) return null;

  for (const child of getToolRegistryChildren(group.id)) {
    if (child.route?.endsWith(`/${toolSlug}`)) return child;
    if (child.id === toolSlug || child.id === `mct-${toolSlug}`) return child;
  }

  return null;
}

export function resolveLevel3DetailRoute(
  item: ToolRegistryEntry,
  categoryId: string,
  groupId: string,
): string | null {
  const route = item.route?.trim();
  if (!route) return null;
  const groupRoute = getToolRegistryGroupRoute(categoryId, groupId);
  if (route === groupRoute) return null;
  return route;
}

export function categoryHasNestedLevel3(categoryId: string): boolean {
  return categoryId === "agent-brain-memory";
}
